# Generated by Django 4.1.2 on 2022-10-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=100)),
                ('nombre_cli', models.CharField(max_length=100)),
                ('apelido_cli', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=70, null=True, unique=True)),
                ('tipo_cli', models.BooleanField(default=False)),
                ('estado_cli', models.BooleanField(default=False)),
                ('fk_id_direccion', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
