# Generated by Django 4.1.1 on 2022-10-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentsApp', '0002_remove_usuarios_id_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('nombre_autor', models.CharField(max_length=100)),
                ('precio', models.FloatField(blank=True, null=True, verbose_name='$')),
                ('img_url', models.CharField(max_length=200)),
                ('fk_id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsApp.categoria')),
            ],
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='fk_id_direccion',
            new_name='direccion',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('detalle_alquiler_venta', models.BooleanField(default=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('fk_id_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsApp.usuarios')),
                ('fk_id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsApp.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.FloatField(blank=True, null=True)),
                ('fk_id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsApp.documento')),
            ],
        ),
    ]
