# Generated by Django 4.1.2 on 2022-10-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsApp', '0003_categoria_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='fk_id_categoria',
            new_name='fk_categoria',
        ),
    ]
