# Generated by Django 4.1.2 on 2022-10-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsApp', '0004_rename_fk_id_categoria_documento_fk_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fk_id_clie',
            new_name='fk_clie',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fk_id_doc',
            new_name='fk_doc',
        ),
    ]
