# Generated by Django 4.1.2 on 2022-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsApp', '0005_rename_fk_id_clie_pedido_fk_clie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='detalle_alquiler_venta',
            field=models.CharField(max_length=100),
        ),
    ]
